# Generated by Django 5.2 on 2025-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_country_of_origin_product_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Брутто вес'),
        ),
    ]
