# Generated by Django 5.2 on 2025-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_gross_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('SOLD', 'sold'), ('SALE', 'sale')], default='NEW', max_length=50, verbose_name='Статус продукта'),
        ),
    ]
